name: Build and Push Docker

on:
  push:
    branches: [ "master" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          # This tells Docker to use the 'backend' folder as the home for the build
          context: ./backend
          # This points directly to the Dockerfile inside that folder
          file: ./backend/Dockerfile
          push: true
          # Replace 'devops-project' with whatever name you want on Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
